Repository scipy/scipy_doctest, pull requests merged in 2024-03, with the labels that each got.

#136 Add DTConfig.pytest_extra_{ignore,skip,xfail} flags
  scpdt/impl.py
  scpdt/plugin.py
Labels: enhancement, pytest-plugin

#140 BUG: fix default stopwords list
  scpdt/impl.py
Labels: bug

#138 BUG: more robust filter DeprecationWarnings
  scpdt/plugin.py
Labels: maintenance, pytest-plugin

#139 DOC: discuss some gotchas in README
  README.md
Labels: documentation

#145 MAINT: close the figures before backend change
  scpdt/util.py
Labels: maintenance

#131 MAINT: refine installation of core and test dependencies
  .github/workflows/pip.yml
  pyproject.toml
  scpdt/tests/test_pytest_configuration.py
  scpdt/tests/test_skipmarkers.py
  scpdt/tests/test_testmod.py
Labels: maintenance

#141 ENH: make OutputChecker pluggable
  scpdt/impl.py
  scpdt/plugin.py
  scpdt/tests/test_pytest_configuration.py
  scpdt/tests/test_runner.py
Labels: enhancement
